package:
  name: catch2
  version: 2.4.0

source:
  url: https://github.com/catchorg/Catch2/releases/download/v2.4.0/catch.hpp
  md5: fb293b2100b23f6567c0fb683c485d87
  sha1: 1670a86d497ae956fbc244a19723629447b56f0e
  sha256: 41522232a2459bb0a078cb1fc8c20c0c082fd762afe2fb54cbb94f1aa538e244

build:
  # If the installation is complex, or different between Unix and Windows, use
  # separate bld.bat and build.sh files instead of this key.  Add the line
  # "skip: True  # [py<35]" (for example) to limit to Python 3.5 and newer, or
  # "skip: True  # [not win]" to limit to Windows.

